### ISSUE TITLE
Add County-Level Mobility Data

### ISSUE THREAD

**Issue by johnhryhorchuk** [texas-2036/covid_tracker#36]
Add county mobility data section that leaves viewers with a clear understanding of the mobility impacts of distancing efforts/quarantines and then shows how quickly/slowly people have responded to the gradual re-opening of the economy. 

This analysis should include include:

1. graphically representing rates of mobility change versus a baseline position on a daily basis (i.e., April 26, 2020 had 40% less movement than April 26, 2019; April 27 had 35% less movement than April 27, 2019)

 2. breakdown data to show where people are going/not going (e.g., 40% decline in visiting restaurants on April 26 changed to 20% decline in visiting restaurants on May 6). See charts below from Google.

<img width="737" alt="Screen Shot 2020-05-02 at 10 25 37 PM" src="https://user-images.githubusercontent.com/64703540/80897999-009d2a00-8cc4-11ea-8b2e-85093fc0e34e.png">

**Comment by mrworthington** [comment]
We have added Google's Mobility Charts on the County Explorer.
