### ISSUE TITLE
Add State-Level Mobility Data

### ISSUE THREAD

**Issue by johnhryhorchuk** [texas-2036/covid_tracker#37]
Add statewide mobility data section that leaves viewers with a clear understanding of the mobility impacts of distancing efforts/quarantines and then show how quickly/slowly people respond to the gradual re-opening of the economy. 

This analysis should include include 
(a) graphically representing overall rate of mobility change versus a baseline position on a daily basis (i.e., April 26, 2020 had 40% less movement than April 26, 2019); 

(b) using a state map with a time-elapse function to show where people were more/less active at different times. This would operate like the time-elapse infection map in one of the other issues -- basically, you click play at the bottom of a map of Texas and see the counties dip into varying depths of blue due to movement reduction, then as we reach May, it starts to lighten and may reach baseline (white) or increased (red) in certain pockets.  This would use daily data, starting around March 1.

(c) breakdown data to show where people are going (e.g., 40% decline in visiting restaurants on April 26 changed to 20% decline in visiting restaurants on May 6) like what google
<img width="714" alt="Screen Shot 2020-05-02 at 10 30 11 PM" src="https://user-images.githubusercontent.com/64703540/80898067-920c9c00-8cc4-11ea-919c-9ee2969b39ca.png">
 has.

**Comment by mrworthington** [comment]
We have added this with Google's Mobility Data.
