### ISSUE TITLE
Add Trend Line for Hospitalization Rate Over Time

### ISSUE THREAD

**Issue by johnhryhorchuk** [texas-2036/covid_tracker#45]
Request of Dell Med

**Comment by mrworthington** [comment]
As of today, we've added multiple trend lines for hospital capacity.
<img width="1445" alt="Screen Shot 2020-07-13 at 4 10 28 PM" src="https://user-images.githubusercontent.com/8171106/87362392-622f0f80-c523-11ea-8879-771756de4da5.png">
