### ISSUE TITLE
Add Population Health Charts

### ISSUE THREAD

**Issue by mrworthington** [texas-2036/covid_tracker#53]
On the back-end, the data has already been cut to report on incidence and fatalities by Race, Age, and Gender at the statewide level. We now just need to draw the charts. My initial ideas were to start integrating some horizontally stacked bar charts to visualize these. Something that would look a lot like the charts below. We may do pie charts, but that may feel bulky in our current layout and pie charts have a lot of controversy around them that I'd like to avoid. 

<img width="1173" alt="Screen Shot 2020-05-15 at 4 41 15 PM" src="https://user-images.githubusercontent.com/8171106/82098686-0d118180-96cb-11ea-884b-8777631e20a5.png">

**Comment by johnhryhorchuk** [comment]
This works for me. For a moment there, I thought you had disease data by education level and/or income, which would be wonderful to include.

**Comment by mrworthington** [comment]
That level of granularity would be awesome.

**Comment by mrworthington** [comment]
These have been implemented under our "Population Health Section" on the state explorer. Closing this issue for now. Future issues can be opened to establish any improvements or enhancements to the work in our population health charts.
