### ISSUE TITLE
Harris County ICU beds availability not working under County Explorer

### ISSUE THREAD

**Issue by LisaKirsch-DellMed** [texas-2036/covid_tracker#54]

**Comment by mrworthington** [comment]
That TSA, for whatever reason, has a 0 on the place of the denominator value. And because you can’t divide by 0, it throws an error. This is the second time it’s been pointed out. I need to write a conditional statement that accounts for weird issues like this, that doesn’t look so 🤖 speak.

**Comment by mrworthington** [comment]
That TSA, for whatever reason, has a 0 on the place of the denominator value. And because you can’t divide by 0, it throws an error. This is the second time it’s been pointed out. I need to write a conditional statement that accounts for weird issues like this, that doesn’t look so 🤖 speak.

**Comment by LisaKirsch-DellMed** [comment]
Got it. I have some more asks from Parker. Will submit via Github.

----

LISA KIRSCH, MPAff
Senior Policy Director

Dell Medical School  |  The University of Texas at Austin
o: 512-495-5131  |  dellmedschool.utexas.edu

**Comment by mrworthington** [comment]
Example Screenshot of "-Inf" Error:
<img width="1447" alt="Screen Shot 2020-05-19 at 10 51 48 AM" src="https://user-images.githubusercontent.com/8171106/82348748-e4390700-99be-11ea-825a-acf8c5855081.png">

**Comment by mrworthington** [comment]
This has been fixed in the update improving all availability rates (Gen, ICU, and Vents) using the new time series data that DSHS provides. See below:

<img width="1680" alt="Screen Shot 2020-06-16 at 1 43 41 PM" src="https://user-images.githubusercontent.com/8171106/84826159-670dab80-afd7-11ea-90c2-9a1b77c1371b.png">

**Comment by mrworthington** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Harris County](https://trello.com/c/I6JHZWJP/2-fix-harris-county)
